use_frameworks!

target 'LocalizationManager_Example' do
  pod 'LocalizationManager', :path => '../'

  target 'LocalizationManager_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
